### ISSUE TITLE
Separate room support

### ISSUE THREAD

**Issue by markunca** [lynxcs/homebridge-ct200#1]
Hi,
firstly thanks for adding this to homebridge. I was planning it but was not to find time for it :-)

Are you planning to add also multiroom support as I am having several rooms?

Thanks

**Comment by markunca** [comment]
It is achievable by using get /zones/list

This what I get
`{"id":"/zones/list","type":"zoneArray","writeable":0,"recordable":0,"value":[{"id":1,"name":"TGl2aW5nIHJvb20=","icon":"living room","program":1,"temp":25.5,"status":"low battery"},{"id":2,"name":"QmF0aHJvb20=","icon":"bathroom","program":3,"temp":25.3,"status":"idle"},{"id":3,"name":"S2lkcm9vbQ==","icon":"kids room","program":3,"temp":25.2,"status":"idle"},{"id":4,"name":"V29ya3Jvb20=","icon":"study","program":3,"temp":24.8,"status":"low battery"},{"id":5,"name":"QmVkcm9vbQ==","icon":"bedroom","program":3,"temp":24,"status":"idle"},{"id":6,"name":"R3Vlc3Ryb29t","icon":"guest room","program":2,"temp":23.9667,"status":"low battery"}]}`

**Comment by lynxcs** [comment]
Hi, I don't have a multiroom setup myself, so I'm having a hard time understanding what kind of functionality you're looking for.
Do you want each zone to show up as a separate temperature sensor? That shouldn't be too hard to implement.

**Comment by markunca** [comment]
Yes, it will be great to be able to show each room separately. As next step addition, also it will be able to setup each room temperatur through homebridge.

**Comment by lynxcs** [comment]
Hello, I tried to implement the temperature sensors, but it won't be as simple as I thought. I'll have to rewrite the plugin to make it register itself as a "platform" instead of as an accessory. I'll do that when I rewrite the plugin to typescript. Should be done by the next weekend.

**Comment by lynxcs** [comment]
I'm closing this issue as due to university I have limited time to work on this project. If you figure out a simple way to do this, I'll review and accept a pull request. With the recent release I believe the plugin is functional-enough for daily use.

EDIT: Multi-room support is now available
