### ISSUE TITLE
Support for multiple Radiator Thermostats / rooms

### ISSUE THREAD

**Issue by AxDevl** [lynxcs/homebridge-ct200#13]
Right now, the plugin works great! However, I have many rooms on my app which each one has the Bosch Radiator thermostats. I have seen when you change the zone it will read the other room however when said in the original release that it isn't yet functional. 

Anyone apart from the creator has found a fix or a work around?

**Comment by lynxcs** [comment]
Someone found a workaround with child bridges that works for the time being: #10

**Comment by AxDevl** [comment]
Ah that's great, Is there a planned update with anything new soon?

**Comment by AxDevl** [comment]
Also, is there a way to remove the away and advanced options as I don't use them?

**Comment by lynxcs** [comment]
Currently, there is no way (as far as I know) to remove/hide them within home app. I'm currently working on a rewrite, which will feature support for multiple devices and I'll be sure to include the option of hiding those options.

Other than that, there is nothing planned.

**Comment by AxDevl** [comment]
Thank you for your determination and the quick response times. By the time Bosch even adds HomeKit support to this, its probably never. I think it a good product in terms of the design however just the lack of updates and overall compatibility that it isn't in the Bosch home app (and HomeKit) makes it a not good product to recommend to certain people. People would choose like the Google Nest Thermostat or Hive.

All I need is stability of changing temperature in rooms, that all I need which this plugin does amazingly. I do use a Bosch adapter converter which doesn't affect the use.

**Comment by lynxcs** [comment]
The rewrite is now in the main repo and on npm. Please test it out and let me know if everything is working correctly for multiple devices. Currently, the Away and Advance switches are not implemented yet.

Note: the config format has changed, since it's now a platform instead of an accessory.

**Comment by AxDevl** [comment]
Hi, I have tried the new update and it is just stunning! I have just seen you have updated it again half an hour ago so let me tried this newer update. Thanks, for updating this plugin.

**Comment by lynxcs** [comment]
That's good to hear! I'm closing this issue as it's very similar to #10. I'll keep that issue open for the time being, until I iron out all the bugs. If you encounter anything wrong, please comment in that issue thread.

Thank you for your feedback and testing!
