### ISSUE TITLE
v2.0.4 completely broke the plugin for me

### ISSUE THREAD

**Issue by fate8383** [lynxcs/homebridge-ct200#15]
I am looking at jason file and I see two set of config now, and logs show errors. tried to remove one of the config from jason, still fails. 

first error
No plugin was found for the accessory "ct200" in your config.json. Please make sure the corresponding plugin is installed correctly.

second error
TypeError: Cannot read properties of undefined (reading 'forEach')
    at CT200Platform.discoverDevices (/usr/lib/node_modules/homebridge-ct200/src/platform.ts:200:30)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-ct200/src/platform.ts:183:18)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:173:14)

**Comment by fate8383** [comment]
ok removes old "accessory" from jason and kept the new "platform" also zone is mandatory now I think, so added zone as well and it is working again. It is a bit tricky that you have changed type from accessory to platform, many will not be able to edit this on jason file, which is very sensitive to touch :) you might want to ad to do wiki for help. Thanks a lot for the good work!
I am about to get some radiator valves goes with ct200, would this be added smoothly with this plugin as well?, i think I have to make zones for each correct?

**Comment by lynxcs** [comment]
Everything from V2.0.0 upwards is a complete rewrite, which changes the config file format.
The new version has support for multiple devices. If the radiator valves use the same API as the CT200, then yes, most likely it will work.

Each 'zone' is a separate thermostat. So, if you want to control all the temperatures separately (and the bosch app allows it), you have to make zone for each.
