### ISSUE TITLE
Issues while installing homebridge-CT200

### ISSUE THREAD

**Issue by eronnes** [lynxcs/homebridge-ct200#18]
Can you help me on this, are these warnings or should do some additional updates?

npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client

**Comment by lynxcs** [comment]
These are from dependencies of bosch-xmpp package, which this plugin uses. These warnings are not necessarily bad, but this is something that the developer of bosch-xmpp must fix. Until then, these warnings will remain.

You shouldn't be worried. Closing.
