### ISSUE TITLE
CT100 support

### ISSUE THREAD

**Issue by arsenbabic** [lynxcs/homebridge-ct200#20]
**Is your feature request related to a problem? Please describe:**

I'm wondering would it be possible to expand support to CT100 devices as well?

**Comment by lynxcs** [comment]
From what I can find, CT100 uses 'nefit' API, not 'EasyControl'. You are welcome to try the plugin with CT100 though I'm doubtful it will work.
For nefit devices you could instead try this plugin: homebridge-nefit-easy

**Comment by arsenbabic** [comment]
You're 100% correct. "nefit" works like a charm! Thanks a lot!
