### ISSUE TITLE
[CT200] SyntaxError encountered while sending request! Double-check login details!

### ISSUE THREAD

**Issue by Barclay2k** [lynxcs/homebridge-ct200#22]
**Describe Your Problem:**
I've checked, and double checked the details on the config.  The account password matches what I use to login to the Bosch account.  
The access key is correct... but in the Bosch App it's called 'Access code' - I removed the spaces when entering it in the config.
Serial key is correct... but in the Bosch App it's called 'Serial number'.  

All I keep getting in HomeBridge is the following:

[CT200] SyntaxError encountered while sending request! Double-check login details!

**Logs:**
[CT200] SyntaxError encountered while sending request! Double-check login details!

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge 4442",
        "username": "0E:BC:22:31:44:42",
        "port": 51920,
        "pin": "440-36-562"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "access": "zFjBAV9ywfZyXPpV",
            "serial": "101205381",
            "password": "XXXXXX-XXXXXX-XXXXXX",
            "away": true,
            "zoneInterval": 2,
            "auxInterval": 5,
            "zones": [
                {
                    "index": 1,
                    "name": "Thermostat"
                }
            ],
            "platform": "CT200"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**:v2.2.0
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by Barclay2k** [comment]
I've worked out the password for your BOSCH ID account is the WRONG one to use.   You need to go to 'Settings' > 'Personal' > 'Change Password' and set a password here. 

With the current EasyControl - you only use the BOSCH ID to authenticate.

**Comment by lynxcs** [comment]
Great that you figured it out yourself! I'll add these instructions to the README so that other people with the same problem can see the solution. Closing.
