### ISSUE TITLE
Over 30C crashes plug-in.

### ISSUE THREAD

**Issue by Barclay2k** [lynxcs/homebridge-ct200#24]
Thanks. Dropping to 5C works well, and errors cleared.

But I thought I would experiment in the other direction. it appears the EasyConnect App/CT200 only allows temperature settings between 5C and 30C.  Currently the homebridge plug-in let’s you go higher, so if you set the temp via HomeKit to 30.5C or higher… it’s not an accepted value and crashes the plug-in in homebridge.   I presume the 5C to 30C is the same for all, are you able to put a 30C limit?

Simon

Sent from my iPhone

> On 7 Jan 2022, at 21:25, Domas K. ***@***.***> wrote:
> 
> ﻿
> Closed #23.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

_Originally posted by @Barclay2k in https://github.com/lynxcs/homebridge-ct200/issues/23#issuecomment-1007777535_

**Comment by lynxcs** [comment]
Just tested it myself, 5C to 30C is the allowed range.

Limit added with latest release. Closing.
