### ISSUE TITLE
homebridge 2.0 support 

### ISSUE THREAD

**Issue by rionshin** [lynxcs/homebridge-ct200#35]
**Is your feature request related to a problem? Please describe:**

Homebridge will be releasing new version that will introduce breaking changes to some plugin 

**Describe the solution you'd like:**
@lynxcs  What is the plan for supporting Homebridge 2.0 - will the plugin be impacted and will it be easy to make it compatible with 2.0.

**Comment by lynxcs** [comment]
Hi, currently there is no plan to support homebridge 2.0, at least from me. I will happily accept PR's if they appear, but in general - this repo/project is not maintained anymore, since I don't have access to CT200 device nor the motivation to keep working on it.

**Comment by rionshin** [comment]
> Hi, currently there is no plan to support homebridge 2.0, at least from me. I will happily accept PR's if they appear, but in general - this repo/project is not maintained anymore, since I don't have access to CT200 device nor the motivation to keep working on it.

I will fork the code to review it and check for break changes, and if i found something i can fix it and push it for your review.

**Comment by rionshin** [comment]
@lynxcs  i check the code and there is no sign of old code that is depreciated in Homebridge 2.0 , so it can be used with coming homebridge 2.0. 
cheers

**Comment by lynxcs** [comment]
That's fantastic, closing this issue.
