### ISSUE TITLE
Off mode

### ISSUE THREAD

**Issue by markunca** [lynxcs/homebridge-ct200#4]
I think Homekit Off mode should refer to EasyControl Away mode which can be triggered by /system/awayMode and targetted temperature for Away.
WDYT?

**Comment by markunca** [comment]
Btw also is possible to turn off cooling in setup of thermostat - here example with heatOnly setup - https://github.com/PJCzx/homebridge-thermostat

**Comment by lynxcs** [comment]
I'll look into turning off the cooling option, didn't know such a thing even existed. As for off mode to refer to away mode I'm not sure. When you turn the thermostat to "Off" in homebridge, it stops showing the target temperature, and only shows the current temperature. The result is that you don't quite know what the away mode temperature is set to (unless you check the easycontrol app). Another reason to keep it as a switch, is that it's easier to apply automations ( When leaving -> turn on away mode switch; I'm not sure if such an options exists for thermostat)

**Comment by lynxcs** [comment]
Removed the "Cool" and "Off" options, as those were not needed. Only "Heat" (representing manual mode) and "Auto" (representing scheduled mode) remains. Now it shows up as a single button in homekit, without needed to select anything. Decided to keep the "Away mode" switch as I think that's the better way to do it.

Newest version implementing these fixes is v1.1.1 on npm.
