### ISSUE TITLE
“Alarm”

### ISSUE THREAD

**Issue by Don-van-Houts** [lynxcs/homebridge-ct200#8]
What do you mean by "Edit the the config.json and add the _**Alarm accessory**_ e.g:"?

Greetings Don.

**Comment by lynxcs** [comment]
Whoops! Copied the readme from another project and forgot to change it! Thank you for pointing it out!
Fixed.
(in case this was a genuine question: the example configuration is correct, but be sure to change "access", "serial" and "password")
